name: tweet-commit
description: Tweet an Awesome List entry from a commit
author: Carlos Pereira Atencio
branding:
  color: blue
  icon: twitter
inputs:
  trigger_keyword:
    description: Trigger keyword to tweet a specific commit
    required: false
    default: Tweet!
runs:
  using: docker
  image: Dockerfile
  args:
  - ${{ inputs.trigger_keyword }}
